// templates/VtPagination.vue
<template>
        <pagination
                :options="props.optionsObj"
                :records="props.records"
                :per-page="props.perPage"
                :value="props.page"
                @input="page => props.setPage(page)"/>
</template>

<script>
    import Pagination from 'v-pagination-3'

    export default {
        name: "MyPagination",
        components: {
            Pagination
        },
        props: ['props']
    }
</script>

// lib/components/VtPagination.jsx
import RLPagination from "./renderless/RLPagination";
import Pagination from "vue-pagination-2";

export default {
    name: 'VtPagination',
    components: {RLPagination, Pagination},
    render(h) {
        return <r-l-pagination scopedSlots={
            {
                default: function (props) {
                    let pagination = props.options.infinite ? '': <pagination
                        options={props.optionsObj}
                        for={props.name}
                        vuex={props.vuex}
                        records={props.records}
                        per-page={props.perPage}
                        page={props.page}
                        onPaginate={page => props.setPage(page)}>
                    </pagination>

                    return props.override ? h(
                        props.override,
                        {
                            attrs: {props}
                        }
                    ) : pagination
                }
            }
        }
            >

            </r-l-pagination>
        }
}
