// templates/VtTableBody.vue
<template>
    <tbody>
    <vnodes :vnodes="props.slots.prependBody"/>
    <vt-no-results-row v-if="props.data.length === 0"/>
    <table-rows v-for="(row,index) in props.data"
                :row="row"
                :index="props.initialIndex + index + 1"
                :renderChildRow="props.hasChildRow && props.openChildRows.includes(row[props.uniqueRowId])"
                :key="index"
    />
    <vnodes :vnodes="props.slots.appendBody"/>
    </tbody>
</template>

<script>
    import VtNoResultsRow from 'v-tables-3/compiled/components/VtNoResultsRow'
    import VtTableRow from 'v-tables-3/compiled/components/VtTableRow'
    import VtChildRow from 'v-tables-3/compiled/components/VtChildRow'

    export default {
        name: "MyTableBody",
        props: ['props'],
        components: {
            VtNoResultsRow,
            VtTableRow,
            VtChildRow,
            vnodes: {
                functional: true,
                render: (h, ctx) => ctx.props.vnodes
            },
            TableRows: {
                functional: true,
                render(h, ctx) {
                    var props = ctx.data.attrs;

                    // TODO: add group row

                    var data = [
                        h('vt-table-row', {
                            props
                        })
                    ];

                    if (props.renderChildRow) {
                        data.push(h('vt-child-row', {
                            props
                        }))
                    }

                    return data
                }
            }
        }
    }
</script>

// lib/components/VtTableBody.jsx
import RLTableBody from "./renderless/RLTableBody";
import VtNoResultsRow from "./VtNoResultsRow";
import VtTableRow from "./VtTableRow";
import VtGroupRow from "./VtGroupRow";
import VtChildRow from "./VtChildRow"

export default {
    name: 'VtTableBody',
    components: {RLTableBody, VtNoResultsRow, VtTableRow, VtChildRow, VtGroupRow},
    render() {
        return <r-l-table-body scopedSlots={
            {
                default: function (props) {
                    var rows = [];
                    var currentGroup;

                    props.data.forEach((row, index) => {
                        if (props.groupBy && props.source === 'client' && row[props.groupBy[0]] !== currentGroup) {
                            rows.push(<vt-group-row row={row}/>)
                            currentGroup = row[props.groupBy[0]]
                        }

                        if (props.canToggleGroups && props.collapsedGroups.includes(currentGroup)) {
                            return;
                        }

                        rows.push(<vt-table-row row={row} index={props.initialIndex + index + 1}/>)
                        if (props.hasChildRow && props.openChildRows.includes(row[props.uniqueRowId])) {
                            rows.push(<vt-child-row row={row} index={props.initialIndex + index + 1}/>)
                        }
                    });

                    return props.override ? h(props.override, {
                        attrs: {props}
                    }) : <tbody>
                    {props.slots.prependBody}
                    {props.data.length===0 ? <vt-no-results-row/> : ''}
                    {rows}
                    {props.slots.appendBody}
                    </tbody>
                }
            }
        }
            >
            </r-l-table-body>
        }
}
