// lib/components/VtHeadingsRow.jsx
import RLHeadingsRow from "./renderless/RLHeadingsRow";
import VtTableHeading from "./VtTableHeading";

export default {
    name: 'VtHeadingsRow',
    components: {RLHeadingsRow, VtTableHeading},
    render() {
        return <r-l-headings-row scopedSlots={
            {
                default: function (props) {

                    var headings = [];

                    if (props.selectable) {
                        var checkbox = props.selectable === 'single' ? '' : <input type="checkbox" onClick={props.selectAll}/>
                        headings.push(<th>
                            {checkbox}
                        </th>)
                    }

                    if (props.childRowTogglerFirst) {
                        headings.push(<th/>);
                    }

                    props.columns.map(function (column) {
                        headings.push(
                            <vt-table-heading column={column}/>
                        );
                    });

                    if (props.childRowTogglerLast) {
                        headings.push(<th/>);
                    }

                    return <tr>
                        {headings}
                    </tr>
                }
            }
        }>
        </r-l-headings-row>
    }
}

// templates/VtHeadingsRow.vue
<template>
    <tr>
        <th v-if="props.childRowTogglerFirst"></th>
        <vt-table-heading v-for="(column, i) in props.columns" :key="i" :column="column"/>
        <th v-if="props.childRowTogglerLast"></th>
    </tr>
</template>

<script>
    import VtTableHeading from 'v-tables-3/compiled/components/VtTableHeading'

    export default {
        name: "MyHeadingsRow",
        props: ['props'],
        components: {
            VtTableHeading
        }
    }
</script>

<style scoped>

</style>
